github: [jamesmudd]
#patreon: # Replace with a single Patreon username
#open_collective: # Replace with a single Open Collective username
#ko_fi: # Replace with a single Ko-fi username
#tidelift: maven/io.jhdf:jhdf
#community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: jamesmudd
#issuehunt: # Replace with a single IssueHunt username
#otechie: # Replace with a single Otechie username
custom: ['https://www.paypal.me/jamesmudd/10']
buy_me_a_coffee: jamesmudd
